### ISSUE TITLE
Physics Issues

### ISSUE THREAD

**Issue by docmop** [jrodrigv/PhysicsRangeExtender#2] opened 2017-04-18 18:47 UTC
I have a great many issues with physics of other vessels when switching to them.

1) Station in orbit wobbles like crazy and do not stop
2) SEP Ground Stations get flung through the air or just explode
3) The rover I was driving before the switch just vanished (exploded?)

Is there any known incompatibility (maybe with with Kerbal Joint reinforcement) or something like that?

[KSP.log](https://github.com/jrodrigv/PhysicsRangeExtender/files/930721/KSP.txt)

**Comment by jrodrigv** [comment] 2017-04-18 18:59
1. I think the station is not really wobbling. I think the shadows are! Are you using scaterer, eve or RSS? I have seen this problem playing with RSSVE. This is not an issue related with this mod.

2 & 3. This problem arise when the terrain get unloaded - For example if you put your rover on the runway this will not happen because the runway is a static object. To avoid this situation you can use KerbalKonstruct - I have explained this on the mod thread.

**Comment by docmop** [comment] 2017-04-18 19:01
1. The station IS wobbling, the parts are moving relative to each other like the whole station was made out of jelly
2 & 3 The exploding vessels where positioned on the KSP static. One near the admin building, one ad R&D

**Comment by jrodrigv** [comment] 2017-04-18 19:09
1. I'll need to see a video for the first one. Maybe I can send you one from mine. I think it is a visual effect related with light/shadow issue but let see.

2. Sometimes they suddenly disappear from the BDArmory vessels list (maybe it is vessel switcher bug I have to check this) but they still there. Can you try to click the key to switch to the next/previous vessel?

**Comment by docmop** [comment] 2017-04-18 19:16
1. It looked like a oscillation within the docking ports that connect parts of the station. Can't say if there was more inter part wobble. DEFINITELY not a shadow or graphics issue. The screen was slightly shaking from the movement of the stations COM too.

2. I have used the stock switch buttons. They where gone. I could switch to some ripped of parts of the SEP that was build near the admin building. The parts where flying* at high speeds through the air. 

*Flying means they where flung (catapulted) to a random direction and currently freefalling.

**Comment by jrodrigv** [comment] 2017-04-18 19:23
Would you mine to try to reproduce the problem using an stock KSP version? I would like to reproduce it locally with some craft file during this week. 

Maybe I will not be able to fix it because I know we are almost reaching the limit of what KSP/Unity can handle but I would like to analyse the problem

**Comment by Janoxigen** [comment] 2017-05-01 22:06
Dunno if it helps (because maybe the bug was already fixed) but i just had the same problem.
All ships and planes i launched started to wobble around after some time - physical wobbling which even the SAS could not prevent. Not just the parts were shaking relative to each other, but also the meshes each part consists of.
The symptoms occured also on stock-only crafts.
The shaking grew in intensity over time. It didn't stop after decoupling stages, which also continued wobbling. Even other crafts that i switched to were already wobbling.


...When i EVA'd a Kerbal he was shaking too.
![20170501220631_1](https://cloud.githubusercontent.com/assets/28275061/25596277/a567d074-2ec8-11e7-9e71-c7866cb8c220.jpg)

Timewarping didn't help either.
So i looked through my mods and found the "PhysicsRangeExtender"(v1.1.0 i think) folder which came together with the [BDArmory.0.2.1.0_04132017](https://github.com/PapaJoesSoup/BDArmory/releases/tag/v0.2.1.0) folder and then this thread here. Seeing it as not finished i continued my search.
After i installed the [latest](https://github.com/jrodrigv/PhysicsRangeExtender/releases/tag/1.2.0) version of PhysicsRangeExtender(ofc deleting the old one) the bug disappeared.

hope that helps a lilbit

**Comment by jrodrigv** [comment] 2017-05-04 19:50
So I think I have finally manage to reproduce and to find the exact condition when the wobbling starts. 
- If you have a vessel landed (runway for example) 
- Then using HyperEdit you put a new vessel into orbit, that vessel will be wobbling.

However if you switch back to the landed vessel and you make the landed vessel to fly, then if you switch back to your orbiting vessel you will see how the wobbling stop.

**Closed** 2017-06-06 11:57 UTC
